#!/bin/bash

set -e
set -x

mysqld --initialize-insecure

/usr/sbin/mysqld --user=root &
mysql_pid=$!

until mysqladmin ping &>/dev/null; do
  echo -n "."; sleep 0.2
done

mysql < /tmp/dump.sql

mysql -e "GRANT ALL ON *.* TO root@'%' IDENTIFIED BY '${db.password}' WITH GRANT OPTION;"

mysqladmin shutdown

wait $mysql_pid

tar czvf default_mysql.tar.gz /var/lib/mysql